### ISSUE TITLE
Profile Family Relationship 

### ISSUE THREAD

**Issue by torstees** [ncpi-fhir/ncpi-model-forge#33] opened 2020-10-09 15:41 UTC
# Requester information
Please provide the following information:
Eric Torstenson
VUMC/Anvil

# Request Details
Please provide the following information about what you wanting to accomplish with your model change request: 
While we are using the base profile, Observation, the application of Focus vs Subject isn't entirely obvious with regard to the directionality of the relationship. We propose that by profile that Observation into a Family relationship, we can explicitly define the usage of those two and, hopefully, make querying for them a bit cleaner as well. 

- Who it benefits-
Any group that uses family relationships as part of their dataset. This includes, but isn't limited to trio, traditional pedigree style datasets, etc. 

- Use case-
When specifying a familial relationship, such as a mother/child relationship, one can use Observations with codes specifying a relationship between two patients, however, the names of the properties, Subject and Focus doesn't explicitly indicate which is the parent and which is the child. By creating a FamilyRelationship profile, we can explicitly define which of those two properties applies to which individual.

**Comment by RobertJCarroll** [comment] 2020-10-09 16:05
duplicate of #21

**Closed by RobertJCarroll** 2020-10-09 16:05 UTC
Labels: Model: New request
